apiVersion: v2
name: terminfinder-backend
description: Web Backend f√ºr die Erstellung von Terminumfragen und die Beantwortung dieser.
type: application
version: 0.0.0

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ^18.0.15
    condition: postgresql.enabled
